# frontend/Dockerfile.dev
FROM node:18

WORKDIR /app

COPY package*.json ./

RUN npm install

# Mount the rest of the code via volume in docker-compose
COPY . .

# Start the React development server
CMD ["npm", "start"]
